### ISSUE TITLE
Move chart to helm/charts or ro-charts repository.

### ISSUE THREAD

**Issue by ejether** [reactiveops/rbac-manager#24]
As per discussion, the chart should be moved to a chart specific repository to follow the standard pattern.

**Comment by sudermanjr** [comment]
I think this would be a good candidate for a public upstream chart.

**Comment by ejether** [comment]
Yeah, I think you're right.

**Comment by robscott** [comment]
I've had a PR waiting for a couple weeks now, just referencing it here in case it continues to take a long time to get a response on that front: https://github.com/helm/charts/pull/8958

**Comment by sudermanjr** [comment]
This has been done and is now in https://charts.reactiveops.com/stable

**Comment by faheem-cliqz** [comment]
Where can we find sources for the helm chart? I assume it is not from https://github.com/helm/charts/pull/8958

**Comment by faheem-cliqz** [comment]
Ok found them https://github.com/reactiveops/charts :)

**Comment by sudermanjr** [comment]
I will add something to the README
