### ISSUE TITLE
GKE Cluster Role Binding

### ISSUE THREAD

**Issue by WillPlatnick** [reactiveops/rbac-manager#37]
When working with GKE, you need to create a clusterrolebinding to make your user a cluster admin. A lot of people probably do this step already to get Helm installed, but it might be helpful to have in the docs.

Something like

```kubectl create clusterrolebinding your-user-cluster-admin-binding --clusterrole=cluster-admin --user=your.google.cloud.email@example.org```

**Comment by jorianvo** [comment]
I recently learned from the [Setting up Jenkins on Kubernetes Engine](https://cloud.google.com/solutions/jenkins-on-kubernetes-engine-tutorial) Google documentation that you can use the `gcloud config get-value account` command to get your google email address, so you can make the command even more generic i.e.:

```
kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin \
        --user=$(gcloud config get-value account)
```

**Comment by robscott** [comment]
I've updated the documentation to include this with the latest release, thanks for the idea!

**Comment by c4m4** [comment]
I have this error "ubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin \ter-admin \
        --user=$(gcloud config get-value account)
Error from server (Forbidden): clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "info@devnull.zero" cannot create resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope

**Comment by robscott** [comment]
Hey @c4m4, are you able to see what kind of IAM access you have in this specific project? Are you a GKE Admin? I think you'd need that level of IAM before you were able to modify Kubernetes RBAC. I wrote a bit more about how RBAC and IAM interact on GKE here: https://medium.com/uptime-99/making-sense-of-kubernetes-rbac-and-iam-roles-on-gke-914131b01922

**Comment by c4m4** [comment]
I have two roles in this project:

role: roles/container.clusterAdmin
role: roles/editor

**Comment by robscott** [comment]
Hey @c4m4, sadly I don't think that's quite enough to create a ClusterRoleBinding, which is what this deployment requires. As I recall, the `container.clusterAdmin` only grants infra level permission, not access within the cluster. So your only internal cluster access is likely coming from the `roles/editor` level access which will not be sufficient.

What you likely want on the IAM side is actually `container.Admin` which is the highest level of permission granted for cluster access. This gets confusing as the Kubernetes `cluster-admin` role is the highest level of access, while the GKE IAM `cluster-admin` role doesn't actually grant access within the cluster.

**Comment by robscott** [comment]
To take a look at what various IAM roles gcloud provides, you can run commands like this:

```
gcloud iam roles describe roles/container.clusterAdmin | grep container.role
(no matches)
```

```
gcloud iam roles describe roles/editor | grep container.role

- container.roleBindings.get
- container.roleBindings.list
- container.roles.get
- container.roles.list
```

```
gcloud iam roles describe roles/container.admin | grep container.role

- container.roleBindings.create
- container.roleBindings.delete
- container.roleBindings.get
- container.roleBindings.list
- container.roleBindings.update
- container.roles.bind
- container.roles.create
- container.roles.delete
- container.roles.get
- container.roles.list
- container.roles.update
```

**Comment by c4m4** [comment]
@robscott thanks for the help, using roles/container.admin it works :)
