### ISSUE TITLE
Detect RoleBinding Changes and Repair

### ISSUE THREAD

**Issue by kekoav** [reactiveops/rbac-manager#46]
Thanks for this operator, it is indeed very handy.

Ran across an issue today where a user within a namespace was able to remove a RoleBinding which is managed by RBACManager, but RBACManager didn't notice and/or repair the binding.

To fix, I had to re-apply the definition. It would be great if RBACManager did some more defensive work to ensure the role bindings that were defined were not tampered with. Especially since I haven't found a good way to protect these generated roles from users who need permissions to manage their own roles in the namespaces.

**Comment by robscott** [comment]
You're completely right, that's how one would expect rbac-manager to behave. Although this isn't technically something we've tried to do, it's something that I think is a natural expectation, so it falls somewhere in between bug and enhancement. I'll try to get this in to our next release.
