### ISSUE TITLE
[ Feature Request ] Be able to specify Globs for namespaces

### ISSUE THREAD

**Issue by Typositoire** [reactiveops/rbac-manager#47]
I'm currently creating namespaces dynamically for ephemeral environments. They all follow a pattern but with some uniqueness, it'd be awesome to be able to match on `.*PATTERN.*`

I don't think this is currently possible.

**Comment by Typositoire** [comment]
More info on this. Helm creates namespaces without the ability to add labels other than `name`. For now I'm creating the namespace BEFORE running helm which let me set some labels.

**Comment by robscott** [comment]
Hey @Typositoire, that's a really interesting idea. We're still thinking through the pros and cons of implementing something like this. In the meantime, this [Helm issue](https://github.com/helm/helm/issues/3503) has some discussion about this and references a [workaround](https://gist.github.com/kvudata/12ba57ae1e7f01799aaa7f36350a9b2e) that could help label namespaces with Helm.

**Comment by Art3mK** [comment]
That would be a very nice feature! Why this was closed?

**Comment by lucasreed** [comment]
> That would be a very nice feature! Why this was closed?

It was closed by the requester, so I'm not sure. We'll track through your new issue now (#129)
