### ISSUE TITLE
question about creating new roles

### ISSUE THREAD

**Issue by kostyrev** [reactiveops/rbac-manager#57]
So this software manages bindings of already existing roles but what do you use to create new roles?
Let's say I need to provide users with ability to use port-forward on pods but there is no such clusterrole by default.

**Comment by sudermanjr** [comment]
@kostyrev You are correct, this does not create roles.  We generally find that managing the roles via plain yaml manifests is sufficient for our needs.

**Comment by kostyrev** [comment]
that's what I thought. Thanks!
